<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE databaseChangeLog [
        <!ELEMENT databaseChangeLog (changeSet)*>
        <!ATTLIST databaseChangeLog
                xmlns CDATA #REQUIRED
                xmlns:xsi CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT changeSet (preConditions|sql|comment|dropForeignKeyConstraint|addForeignKeyConstraint|sqlFile)*>
        <!ATTLIST changeSet
                author CDATA #REQUIRED
                id CDATA #REQUIRED>
        <!ELEMENT preConditions (dbms|sqlCheck|foreignKeyConstraintExists|tableExists)*>
        <!ATTLIST preConditions
                onError CDATA #IMPLIED
                onFail CDATA #REQUIRED>
        <!ELEMENT dbms (#PCDATA)>
        <!ATTLIST dbms
                type CDATA #REQUIRED>
        <!ELEMENT sqlCheck (#PCDATA)>
        <!ATTLIST sqlCheck
                expectedResult CDATA #REQUIRED>
        <!ELEMENT sql (#PCDATA)>
        <!ELEMENT foreignKeyConstraintExists (#PCDATA)>
        <!ATTLIST foreignKeyConstraintExists
                foreignKeyName CDATA #REQUIRED
                schemaName CDATA #IMPLIED>
        <!ELEMENT comment (#PCDATA)>
        <!ELEMENT dropForeignKeyConstraint (#PCDATA)>
        <!ATTLIST dropForeignKeyConstraint
                baseTableName CDATA #REQUIRED
                constraintName CDATA #REQUIRED>
        <!ELEMENT addForeignKeyConstraint (#PCDATA)>
        <!ATTLIST addForeignKeyConstraint
                baseColumnNames CDATA #REQUIRED
                baseTableName CDATA #REQUIRED
                constraintName CDATA #REQUIRED
                deferrable CDATA #REQUIRED
                initiallyDeferred CDATA #REQUIRED
                referencedColumnNames CDATA #REQUIRED
                referencedTableName CDATA #REQUIRED>
        <!ELEMENT sqlFile (#PCDATA)>
        <!ATTLIST sqlFile
                endDelimiter CDATA #IMPLIED
                path CDATA #REQUIRED>
        <!ELEMENT tableExists (#PCDATA)>
        <!ATTLIST tableExists
                schemaName CDATA #REQUIRED
                tableName CDATA #REQUIRED>
        ]>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog/1.9"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog/1.9
                  http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-1.9.xsd">
    <!--
        See http://www.liquibase.org/manual/home#available_database_refactorings
        for a list of supported elements and attributes
    -->
    <!--loading the initial dictionry for esaude-->
    <!--<changeSet id="esaude-dictionary-001" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
        </preConditions>
        <comment>Loading the dictionary for esaude........</comment>
        <sqlFile path="sql/dictionary/eSaudeConcepts24102016.sql" />
    </changeSet>-->

    <!--
        Ensure the selected default location actually exists. If it doesn't, set
        the value to the unknown location.
    -->
    <!--Setting the uncode of the database to utf-8 for openmrs
    -->
    <!--<changeSet id="esaude-metadata-database-unicode-001" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
        </preConditions>
        <comment>Changing the unicode of the openmrs database to utf-8</comment>
        <sql>
            ALTER DATABASE openmrs CHARACTER SET utf8 COLLATE utf8_unicode_ci;
        </sql>
    </changeSet>-->
    <changeSet id="esaude-metadata-1" author="psbrandt">
        <preConditions onFail="MARK_RAN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="1">
                select count(*) from location as l, global_property as gp where l.name=gp.property_value and gp.property='default_location';
            </sqlCheck>
        </preConditions>
        <sql>
            update global_property as gp, location as l set gp.property_value=l.name where l.location_id=1 and gp.property='default_location';
        </sql>
    </changeSet>

    <!--reporting_report_design foreign key fixes start here-->
    <changeSet id="esaude-metadata-2" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_ibfk_1" />
        </preConditions>
        <comment>Droping 'reporting_report_design_ibfk_1' and creating a new one  'changed_by for reporting_report_design'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design" constraintName="reporting_report_design_ibfk_1" />
        <addForeignKeyConstraint baseTableName="reporting_report_design" baseColumnNames="changed_by" constraintName="changed_by for reporting_report_design" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-3" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_ibfk_2" />
        </preConditions>
        <comment>Droping 'reporting_report_design_ibfk_2' and creating a new one  'creator for reporting_report_design'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design" constraintName="reporting_report_design_ibfk_2" />
        <addForeignKeyConstraint baseTableName="reporting_report_design" baseColumnNames="creator" constraintName="creator for reporting_report_design" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>
    <changeSet id="esaude-metadata-4-dropping" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="1">
                SELECT COUNT(*) FROM liquibasechangelog WHERE id='esaude-metadata-4' AND author='ningosi';
            </sqlCheck>
        </preConditions>
        <comment>Dropping the liquibase change set that was erronoiusly done</comment>
        <sql>
            DELETE FROM liquibasechangelog WHERE id='esaude-metadata-4' AND author='ningosi';
        </sql>
    </changeSet>

    <changeSet id="esaude-metadata-4-correct" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_ibfk_3" />
        </preConditions>
        <comment>Droping 'reporting_report_design_ibfk_3' and creating a new one  'retired_by for reporting_report_design'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design" constraintName="reporting_report_design_ibfk_3" />
        <addForeignKeyConstraint baseTableName="reporting_report_design" baseColumnNames="report_definition_uuid" constraintName="report_definition_uuid for reporting_report_design" referencedTableName="serialized_object"
                                 referencedColumnNames="uuid" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-5" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_ibfk_4" />
        </preConditions>
        <comment>Droping 'reporting_report_design_ibfk_4' and creating a new one  'retired_by for reporting_report_design'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design" constraintName="reporting_report_design_ibfk_4" />
        <addForeignKeyConstraint baseTableName="reporting_report_design" baseColumnNames="retired_by" constraintName="retired_by for reporting_report_design" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

<!--clearing all the reporting framework changeset to force rebuild at reporting framework restart-->
    <changeSet id="esaude-metadata-6" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
        </preConditions>
        <comment>Clearing all reporting changesets for recreation</comment>
        <sql>
            DELETE FROM liquibasechangelog WHERE id LIKE 'reporting%';
        </sql>
    </changeSet>

    <!--reporting_report_design_resource foreing key naming fixes starts here-->
    <changeSet id="esaude-metadata-7" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_resource_ibfk_1" />
        </preConditions>
        <comment>Droping 'reporting_report_design_resource_ibfk_1' and creating a new one  'changed_by for reporting_report_design_resource'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design_resource" constraintName="reporting_report_design_resource_ibfk_1" />
        <addForeignKeyConstraint baseTableName="reporting_report_design_resource" baseColumnNames="changed_by" constraintName="changed_by for reporting_report_design_resource" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-8" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_resource_ibfk_2" />
        </preConditions>
        <comment>Droping 'reporting_report_design_resource_ibfk_2' and creating a new one  'creator for reporting_report_design_resource'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design_resource" constraintName="reporting_report_design_resource_ibfk_2" />
        <addForeignKeyConstraint baseTableName="reporting_report_design_resource" baseColumnNames="creator" constraintName="creator for reporting_report_design_resource" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-9" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_resource_ibfk_3" />
        </preConditions>
        <comment>Droping 'reporting_report_design_resource_ibfk_3' and creating a new one  'report_design_id for reporting_report_design_resource'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design_resource" constraintName="reporting_report_design_resource_ibfk_3" />
        <addForeignKeyConstraint baseTableName="reporting_report_design_resource" baseColumnNames="report_design_id" constraintName="report_design_id for reporting_report_design_resource" referencedTableName="reporting_report_design"
                                 referencedColumnNames="id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-10" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_design_resource_ibfk_4" />
        </preConditions>
        <comment>Droping 'reporting_report_design_resource_ibfk_4' and creating a new one  'retired_by for reporting_report_design_resource'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_design_resource" constraintName="reporting_report_design_resource_ibfk_4" />
        <addForeignKeyConstraint baseTableName="reporting_report_design_resource" baseColumnNames="retired_by" constraintName="retired_by for reporting_report_design_resource" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>
    <!--reporting_report_processor foreing key naming fixes starts here-->
    <changeSet id="esaude-metadata-11" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_processor_ibfk_1" />
        </preConditions>
        <comment>Droping 'reporting_report_processor_ibfk_1' and creating a new one  'changed_by for reporting_report_processor'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_processor" constraintName="reporting_report_processor_ibfk_1" />
        <addForeignKeyConstraint baseTableName="reporting_report_processor" baseColumnNames="changed_by" constraintName="changed_by for reporting_report_processor" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-12" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_processor_ibfk_2" />
        </preConditions>
        <comment>Droping 'reporting_report_processor_ibfk_2' and creating a new one  'creator for reporting_report_processor'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_processor" constraintName="reporting_report_processor_ibfk_2" />
        <addForeignKeyConstraint baseTableName="reporting_report_processor" baseColumnNames="creator" constraintName="creator for reporting_report_processor" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-13" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_processor_ibfk_4" />
        </preConditions>
        <comment>Droping 'reporting_report_processor_ibfk_4' and creating a new one  'retired_by for reporting_report_processor'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_processor" constraintName="reporting_report_processor_ibfk_4" />
        <addForeignKeyConstraint baseTableName="reporting_report_processor" baseColumnNames="creator" constraintName="retired_by for reporting_report_processor" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-14" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_processor_ibfk_3" />
        </preConditions>
        <comment>Droping 'reporting_report_processor_ibfk_3' and creating a new one  'reporting_report_processor_report_design'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_processor" constraintName="reporting_report_processor_ibfk_3" />
        <addForeignKeyConstraint baseTableName="reporting_report_processor" baseColumnNames="report_design_id" constraintName="reporting_report_processor_report_design" referencedTableName="reporting_report_design"
                                 referencedColumnNames="id" deferrable="false" initiallyDeferred="false" />
    </changeSet>
    <!--reporting_report_request foreing key naming fixes starts here-->
    <changeSet id="esaude-metadata-15" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="reporting_report_request_ibfk_1" />
        </preConditions>
        <comment>Droping 'reporting_report_request_ibfk_1' and creating a new one  'requested_by for reporting_report_request'</comment>
        <dropForeignKeyConstraint baseTableName="reporting_report_request" constraintName="reporting_report_request_ibfk_1" />
        <addForeignKeyConstraint baseTableName="reporting_report_request" baseColumnNames="requested_by" constraintName="requested_by for reporting_report_request" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>
    <!--serialized_object foreing key naming fixes starts here-->
    <changeSet id="esaude-metadata-16" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="serialized_object_ibfk_1" />
        </preConditions>
        <comment>Droping 'serialized_object_ibfk_1' and creating a new one  'serialized_object_changed_by'</comment>
        <dropForeignKeyConstraint baseTableName="serialized_object" constraintName="serialized_object_ibfk_1" />
        <addForeignKeyConstraint baseTableName="serialized_object" baseColumnNames="changed_by" constraintName="serialized_object_changed_by" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-17" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="serialized_object_ibfk_2" />
        </preConditions>
        <comment>Droping 'serialized_object_ibfk_2' and creating a new one  'serialized_object_creator'</comment>
        <dropForeignKeyConstraint baseTableName="serialized_object" constraintName="serialized_object_ibfk_2" />
        <addForeignKeyConstraint baseTableName="serialized_object" baseColumnNames="creator" constraintName="serialized_object_creator" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-18" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <foreignKeyConstraintExists foreignKeyName="serialized_object_ibfk_3" />
        </preConditions>
        <comment>Droping 'serialized_object_ibfk_3' and creating a new one  'serialized_object_retired_by'</comment>
        <dropForeignKeyConstraint baseTableName="serialized_object" constraintName="serialized_object_ibfk_3" />
        <addForeignKeyConstraint baseTableName="serialized_object" baseColumnNames="retired_by" constraintName="serialized_object_retired_by" referencedTableName="users"
                                 referencedColumnNames="user_id" deferrable="false" initiallyDeferred="false" />
    </changeSet>

    <changeSet id="esaude-metadata-19-correcting" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
        <sqlCheck expectedResult="1">
            SELECT COUNT(*) FROM liquibasechangelog WHERE id='esaude-metadata-19' AND author='ningosi';
        </sqlCheck>
        </preConditions>
        <comment>Dropping the liquibase change set that was erronoiusly done</comment>
        <sql>
            DELETE FROM liquibasechangelog WHERE id='esaude-metadata-19' AND author='ningosi';
        </sql>
    </changeSet>

    <!--supply default user for all metadata-->
    <changeSet id="esaude-metadata-19-corrected" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM person where uuid='aa81a280-57e9-11e6-bc5b-507b9dc4c741';
            </sqlCheck>
        </preConditions>
        <comment>Creating person object for user for the metadata creation</comment>
        <sql>
            INSERT INTO person(`gender`, `birthdate`, `birthdate_estimated`, `dead`, `death_date`, `cause_of_death`, `creator`, `date_created`, `changed_by`, `date_changed`, `voided`, `voided_by`, `date_voided`, `void_reason`, `uuid`)
            VALUES('M', '2000-12-01', 1, 0, NULL, NULL, 1, current_date, NULL, NULL, 0, NULL, NULL, NULL, 'aa81a280-57e9-11e6-bc5b-507b9dc4c741');
        </sql>
    </changeSet>
    
    <changeSet id="esaude-metadata-20" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM person_name where uuid='2a1b5f8a-57eb-11e6-9c63-507b9dc4c741';
            </sqlCheck>
        </preConditions>
        <comment>Creating person name and user objects</comment>
        <sqlFile path="sql/metadataUser.sql" />
    </changeSet>

    <changeSet id="esaude-metadata-21" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
        </preConditions>
        <comment>Granting relevant roles to the 'esaude.metadata' user</comment>
        <sql>
            SELECT user_id INTO @user_id FROM users where uuid='f9a19c60-57eb-11e6-a798-507b9dc4c741';
            INSERT INTO user_role(`user_id`,`role`) VALUES(@user_id, 'System Developer');

        </sql>
    </changeSet>

    <!--flags required for poc work-->
    <!--The precondition should check that the patient flags table exists, and that the flag does not already exist-->
    <changeSet id="esaude-metadata-22" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <tableExists tableName="patientflags_flag" schemaName="openmrs" />
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='ELIGIBLES';
            </sqlCheck>
        </preConditions>
        <comment>Creating the 'eligibles' patient flag</comment>
        <sqlFile path="sql/eligibles.sql" />
    </changeSet>
    <!--Dropping the already existing Drug start date flag and provide the correct one-->
    <changeSet id="esaude-metadata-23-correcting" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <sqlCheck expectedResult="1">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='DRUG START DATE';
            </sqlCheck>
        </preConditions>
        <sql>
            SET FOREIGN_KEY_CHECKS = 0;
            DELETE FROM patientflags_flag WHERE name='DRUG START DATE';
            DELETE FROM liquibasechangelog WHERE id="esaude-metadata-23";
            SET FOREIGN_KEY_CHECKS = 1;
        </sql>
    </changeSet>
    <changeSet id="esaude-metadata-23-corrected" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <tableExists tableName="patientflags_flag" schemaName="openmrs" />
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='DRUG START DATE';
            </sqlCheck>
        </preConditions>
        <comment>Creating the 'DRUG START DATE' patient flag</comment>
        <sqlFile path="sql/drug_start_date.sql" />
    </changeSet>

    <changeSet id="esaude-metadata-24" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <tableExists tableName="patientflags_flag" schemaName="openmrs" />
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='CTZ_PROPHILAXIS';
            </sqlCheck>
        </preConditions>
        <comment>Creating the 'CTZ_PROPHILAXIS' patient flag</comment>
        <sqlFile path="sql/ctz_prophilaxis.sql" />
    </changeSet>
    <changeSet id="esaude-metadata-25-correcting" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <sqlCheck expectedResult="1">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='CD4 FIRST CONSULTATION';
            </sqlCheck>
        </preConditions>
        <sql>
            SET FOREIGN_KEY_CHECKS = 0;
            DELETE FROM patientflags_flag WHERE name='CD4 FIRST CONSULTATION';
            DELETE FROM liquibasechangelog WHERE id="esaude-metadata-25";
            SET FOREIGN_KEY_CHECKS = 1;
        </sql>
    </changeSet>
    <changeSet id="esaude-metadata-25-corrected" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <tableExists tableName="patientflags_flag" schemaName="openmrs" />
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='CD4 FIRST CONSULTATION';
            </sqlCheck>
        </preConditions>
        <comment>Creating the 'CD4 FIRST CONSULTATION' patient flag</comment>
        <sqlFile path="sql/cd4_first_consultation.sql" />
    </changeSet>
    <changeSet id="esaude-metadata-26-correcting" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <sqlCheck expectedResult="1">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='CD4 6 MONTHS LATER';
            </sqlCheck>
        </preConditions>
        <sql>
            SET FOREIGN_KEY_CHECKS = 0;
            DELETE FROM patientflags_flag WHERE name='CD4 6 MONTHS LATER';
            DELETE FROM liquibasechangelog WHERE id="esaude-metadata-26";
            SET FOREIGN_KEY_CHECKS = 1;
        </sql>
    </changeSet>
    <changeSet id="esaude-metadata-26-corrected" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <tableExists tableName="patientflags_flag" schemaName="openmrs" />
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM patientflags_flag WHERE name='CD4 6 MONTHS LATER';
            </sqlCheck>
        </preConditions>
        <comment>Creating the 'CD4 6 MONTHS LATER' patient flag</comment>
        <sqlFile path="sql/cd4_6_months_later.sql" />
    </changeSet>

    <!--fixing system id for the metadata user-->
    <changeSet id="esaude-metadata-27" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="1">
                SELECT count(*) FROM users where uuid='f9a19c60-57eb-11e6-a798-507b9dc4c741';
            </sqlCheck>
        </preConditions>
        <comment>Adding a system Id for the metadata user</comment>
        <sql>
            SELECT user_id INTO @user_id FROM users where uuid='f9a19c60-57eb-11e6-a798-507b9dc4c741';
            UPDATE users SET system_id='ESAUDE METADATA' WHERE user_id=@user_id;
        </sql>
    </changeSet>

    <!--updating form schemas-->
    <changeSet id="esaude-metadata-28" author="ningosi">
        <sqlFile path="sql/update_forms_updated-1.sql" />
    </changeSet>


    <!--strat of form field settings-->
    <changeSet id="esaude-metadata-38" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM form_field WHERE uuid='83cec426-ddce-4c01-a366-9a60bbcc371b';
            </sqlCheck>
        </preConditions>
        <comment>Updating form fileds for vitals</comment>
        <sql>
            SET FOREIGN_KEY_CHECKS = 0;
            SELECT user_id INTO @user_id FROM users where uuid='f9a19c60-57eb-11e6-a798-507b9dc4c741';
            INSERT INTO form_field(`form_id`,`field_id`,`field_number`,`field_part`,`page_number`,`parent_form_field`,`min_occurs`,`max_occurs`,`required`,`changed_by`, `date_changed`,`creator`,`date_created`,`sort_weight`,`uuid`)
            VALUES (37, 765, NULL, NULL, NULL, 2731, NULL, NULL, 0, NULL, NULL , @user_id, '2016-08-25 06:55:35', 250.00000, '83cec426-ddce-4c01-a366-9a60bbcc371b');
        </sql>
    </changeSet>

    <changeSet id="esaude-metadata-39" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM form_field WHERE uuid='5d0d0957-bf98-4508-9499-3047b67a9c3a';
            </sqlCheck>
        </preConditions>
        <comment>Updating form fileds for vitals</comment>
        <sql>
            SELECT user_id INTO @user_id FROM users where uuid='f9a19c60-57eb-11e6-a798-507b9dc4c741';
            INSERT INTO form_field(`form_id`,`field_id`,`field_number`,`field_part`,`page_number`,`parent_form_field`,`min_occurs`,`max_occurs`,`required`,`changed_by`, `date_changed`,`creator`,`date_created`,`sort_weight`,`uuid`)
            VALUES (37, 397, NULL, NULL, NULL, 2731, NULL, NULL, 0, NULL, NULL , @user_id, '2016-08-25 06:55:35', 250.00000, '5d0d0957-bf98-4508-9499-3047b67a9c3a');
        </sql>
    </changeSet>

    <changeSet id="esaude-metadata-40" author="ningosi">
        <preConditions onFail="MARK_RAN" onError="WARN">
            <dbms type="mysql"/>
            <sqlCheck expectedResult="0">
                SELECT COUNT(*) FROM form_field WHERE uuid = 'b65ca6a2-0a62-4499-b32c-e5c1578f4dee';
            </sqlCheck>
        </preConditions>
        <comment>Adding form fields for diagnosis children</comment>
        <sql>
            SELECT user_id INTO @user_id FROM users where uuid='f9a19c60-57eb-11e6-a798-507b9dc4c741';
            INSERT INTO form_field(`form_id`,`field_id`,`field_number`,`field_part`,`page_number`,`parent_form_field`,`min_occurs`,`max_occurs`,`required`,`changed_by`, `date_changed`,`creator`,`date_created`,`sort_weight`,`uuid`)